# Generated by Django 5.2.4 on 2025-07-31 08:37

import django.contrib.auth.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0016_alter_user_unique_together_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='فقط حروف فارسی مجاز است.', regex='^[\\u0600-\\u06FF\\s\\u200c]+$')], verbose_name='نام')),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='فقط حروف فارسی مجاز است.', regex='^[\\u0600-\\u06FF\\s\\u200c]+$')], verbose_name='نام خانوادگی')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='فقط حروف، اعداد و نمادهای @ . _ - * مجاز هستند.', regex='^[A-Za-z0-9@._\\-*]+$')], verbose_name='نام کاربری')),
                ('phone', models.CharField(db_index=True, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^989\\d{2}\\s*?\\d{3}\\s*?\\d{4}$')], verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='آدرس ایمیل')),
                ('activation_code', models.CharField(editable=False, max_length=128, null=True)),
                ('access', models.CharField(choices=[('superuser', 'superuser'), ('admin', 'admin')])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='adminpanel_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='adminpanel_permission_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
