# Generated by Django 5.2.4 on 2025-08-01 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminpanel',
            options={'verbose_name': 'admin panel', 'verbose_name_plural': 'admins panel'},
        ),
        migrations.AlterField(
            model_name='adminpanel',
            name='access',
            field=models.CharField(choices=[('superuser', 'superuser'), ('admin', 'admin')], default='admin', max_length=15),
        ),
        migrations.AlterField(
            model_name='adminpanel',
            name='activation_code',
            field=models.CharField(editable=False, max_length=128, null=True, verbose_name='activation code'),
        ),
        migrations.AlterField(
            model_name='adminpanel',
            name='phone',
            field=models.CharField(db_index=True, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^989\\d{2}\\s*?\\d{3}\\s*?\\d{4}$')], verbose_name='phone number'),
        ),
    ]
