# Generated by Django 5.2.4 on 2025-08-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_adminpanel_options_alter_adminpanel_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpanel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='آدرس ایمیل'),
        ),
    ]
