# Generated by Django 5.2.4 on 2025-08-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_adminpanel_is_admin_alter_adminpanel_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpanel',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='is admin'),
        ),
    ]
