# Generated by Django 5.2.4 on 2025-08-02 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_alter_adminpanel_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpanel',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='ادمین'),
        ),
        migrations.AlterField(
            model_name='adminpanel',
            name='phone',
            field=models.CharField(db_index=True, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن نامعتبر است.', regex='^989\\d{2}\\s*?\\d{3}\\s*?\\d{4}$')], verbose_name='شماره تلفن'),
        ),
    ]
