# Generated by Django 5.2.4 on 2025-08-02 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_adminpanel_is_admin_alter_adminpanel_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='adminpanel',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='adminpanel',
            name='activation_code',
        ),
        migrations.RemoveField(
            model_name='adminpanel',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='adminpanel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adminpanel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='adminpanel',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='adminpanel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='adminpanel',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='adminpanel',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='adminpanel',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='adminpanel',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='adminpanel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='adminpanel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='adminpanel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='adminpanel',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='adminpanel',
            name='username',
        ),
        migrations.AddField(
            model_name='adminpanel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='adminpanel',
            name='access',
            field=models.CharField(choices=[('superuser', 'superuser'), ('admin', 'admin')], default='admin', max_length=15, verbose_name='access'),
        ),
    ]
