# Generated by Django 5.2.4 on 2025-08-03 19:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('consulting', 'مشاوره'), ('sale', 'فروش'), ('spraying', 'سم پاشی')], max_length=10, verbose_name='نوع درخواست')),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='شماره تلفن نامعتبر است.', regex='^989\\d{2}\\s*?\\d{3}\\s*?\\d{4}$')], verbose_name='شماره تلفن')),
                ('message', models.TextField(verbose_name='پیغام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
