# Generated by Django 5.2.4 on 2025-07-28 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_unique_together_user_activation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='فقط حروف فارسی مجاز است.', regex='^[\\u0600-\\u06FF\\s\\u200c]+$')], verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='فقط حروف فارسی مجاز است.', regex='^[\\u0600-\\u06FF\\s\\u200c]+$')], verbose_name='نام خانوادگی'),
        ),
    ]
