# Generated by Django 5.2.4 on 2025-08-02 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='فقط حروف فارسی مجاز است.', regex='^[\\u0600-\\u06FF\\s\\u200c]+$')], verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='فقط حروف فارسی مجاز است.', regex='^[\\u0600-\\u06FF\\s\\u200c]+$')], verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن نامعتبر است.', regex='^989\\d{2}\\s*?\\d{3}\\s*?\\d{4}$')], verbose_name='phone number'),
        ),
    ]
