# Generated by Django 5.2.4 on 2025-08-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0016_alter_user_unique_together_alter_user_first_name_and_more'),
        ('user', '0011_alter_user_is_admin_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-phone', '-date_joined'], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_code',
            field=models.CharField(editable=False, max_length=128, null=True, verbose_name='کد فعالسازی'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['phone'], name='phone'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['username'], name='username'),
        ),
    ]
